"""Markdown rendering for bash-vet vetting reports.

Pure functions: input is one or more shell commands and their CommandVetReport
results, output is a markdown summary suitable for pasting into Claude Code,
Slack, GitHub issues, docs, or piping anywhere.
"""
from __future__ import annotations

from bash_vet_mcp.types import CommandVetReport, Verdict


def _verdict_emoji(v: Verdict) -> str:
    return {
        Verdict.BLOCK: "🛑",
        Verdict.REVIEW: "⚠",
        Verdict.CAUTION: "ℹ",
        Verdict.CLEAN: "✓",
        Verdict.UNVERIFIED: "?",
    }.get(v, "·")


def _truncate(text: str, n: int = 70) -> str:
    text = text.replace("|", "\\|").replace("\n", " ")
    if len(text) <= n:
        return text
    return text[: n - 1] + "…"


def render_vet_results(
    *,
    results: list[tuple[str, CommandVetReport]],
    version: str,
) -> str:
    """Render a list of (command, vet_report) pairs as a one-page markdown summary."""
    lines: list[str] = []
    lines.append("## bash-vet · command vetting report")
    lines.append("")

    counts = {Verdict.BLOCK: 0, Verdict.REVIEW: 0, Verdict.CAUTION: 0, Verdict.CLEAN: 0, Verdict.UNVERIFIED: 0}
    for _, report in results:
        counts[report.verdict] = counts.get(report.verdict, 0) + 1

    summary_bits: list[str] = []
    if counts[Verdict.BLOCK]:
        summary_bits.append(f"**🛑 {counts[Verdict.BLOCK]} BLOCK**")
    if counts[Verdict.REVIEW]:
        summary_bits.append(f"⚠ {counts[Verdict.REVIEW]} REVIEW")
    if counts[Verdict.CAUTION]:
        summary_bits.append(f"ℹ {counts[Verdict.CAUTION]} CAUTION")
    if counts[Verdict.CLEAN]:
        summary_bits.append(f"✓ {counts[Verdict.CLEAN]} CLEAN")
    if counts[Verdict.UNVERIFIED]:
        summary_bits.append(f"? {counts[Verdict.UNVERIFIED]} UNVERIFIED")

    lines.append(f"**Vetted:** {len(results)} commands  ·  " + "  ·  ".join(summary_bits))
    lines.append("")

    # At-a-glance table
    lines.append("| Verdict | Risk | Command | Top finding |")
    lines.append("|---|---:|---|---|")
    for command, report in results:
        emoji = _verdict_emoji(report.verdict)
        verdict_str = f"{emoji} {report.verdict.value.upper()}"
        cmd_cell = f"`{_truncate(command, 60)}`"
        if report.findings:
            top = report.findings[0]
            top_cell = f"`{top.rule_id}` ({top.severity.value})"
        else:
            top_cell = "—"
        lines.append(f"| {verdict_str} | {report.risk_score}/100 | {cmd_cell} | {top_cell} |")
    lines.append("")

    # Detailed findings for each non-CLEAN result
    interesting = [(c, r) for c, r in results if r.verdict != Verdict.CLEAN and r.findings]
    if interesting:
        lines.append("### Findings detail")
        lines.append("")
        for command, report in interesting:
            lines.append(f"**`{_truncate(command, 100)}`**")
            lines.append(f"  · verdict **{report.verdict.value.upper()}**, risk_score **{report.risk_score}/100**, {report.finding_count} finding(s)")
            for finding in report.findings:
                lines.append(
                    f"  - `{finding.rule_id}` ({finding.severity.value}) — "
                    f"{finding.pattern_kind}: {finding.description}"
                )
                if finding.recommendation:
                    lines.append(f"    - 💡 {finding.recommendation}")
            lines.append("")

    lines.append("---")
    lines.append("")
    lines.append(
        f"> ℹ Generated by `bash-vet-mcp-report` v{version}. "
        f"Pipe commands via stdin (`echo 'rm -rf /' | bash-vet-mcp-report`) or invoke as an "
        f"MCP server in Claude Code / Cursor / OpenClaw via the `vet_command` tool."
    )

    return "\n".join(lines)
